# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iCook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iCook
    pod 'URLImage'
    pod 'SDWebImageSwiftUI'



  target 'iCookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iCookUITests' do
    # Pods for testing
  end

end
